"""
Maraging Steel M300 — Plotting Script
======================================
Reads ALL data from pipeline_full_timeseries.json (generated by run_pipeline.py
and updated by update_kinetics.py)

"""

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import json
import os
import sys

# ============================================================
# LOAD DATA FROM JSON
# ============================================================
DATA_FILE = 'pipeline_full_timeseries.json'

if not os.path.exists(DATA_FILE):
    print(f"ERROR: {DATA_FILE} not found!")
    print("Run 'python run_pipeline.py' first to generate it.")
    sys.exit(1)

print("=" * 70)
print("  MARAGING STEEL M300 — PLOTTING SCRIPT")
print("  Reading from: pipeline_full_timeseries.json")
print("=" * 70)

with open(DATA_FILE, 'r') as f:
    data = json.load(f)

# ---- Extract arrays ----
t_s   = np.array(data['time_seconds'])        # time in seconds
t_h   = np.array(data['time_hours'])           # time in hours
TEMPS = data['temperatures_C']                 # [400, 475, 500, 600]

# ---- Extract constants ----
constants = data['constants']
Y_alpha = constants['Y_alpha_Pa']              # 1000e6 Pa
Y_gamma = constants['Y_gamma_Pa']              # 250e6 Pa

# ---- Extract per-temperature kinetic data ----
kd = data['kinetic_data']  # dict keyed by str(T)

print(f"\n  Loaded {data['n_points']} time points, "
      f"{len(TEMPS)} temperatures: {TEMPS}")
print(f"  Time range: {t_h[0]:.4f} — {t_h[-1]:.2f} hours")

# ---- Check what arrays are available ----
sample_k = str(TEMPS[0])
has_gamma = 'f_gamma' in kd[sample_k]
has_ar    = 'ar' in kd[sample_k]

print(f"  Austenite kinetics: {'YES' if has_gamma else 'NO'}")
print(f"  Aspect ratio:       {'YES' if has_ar else 'NO'}")

# ---- Print summary ----
header = f"  {'T(°C)':>6}  {'f_eq':>7}  {'fp(end)':>8}"
if has_gamma:
    header += f"  {'fg(end)':>8}  {'fg_eq':>7}"
header += f"  {'r(end)':>7}  {'YT_peak':>10}"
print(f"\n{header}")
print("  " + "-" * 80)

for T in TEMPS:
    k  = str(T)
    fp = np.array(kd[k]['f_precip'])
    r  = np.array(kd[k]['r_nm'])
    YT = np.array(kd[k]['YT_Pa'])
    feq = kd[k]['f_eq']
    ipk = np.argmax(YT)

    row = f"  {T:>6}  {feq:>7.4f}  {fp[-1]:>8.5f}"
    if has_gamma:
        fg = np.array(kd[k]['f_gamma'])
        fg_eq = kd[k].get('f_gamma_eq', 0.0)
        row += f"  {fg[-1]:>8.4f}  {fg_eq:>7.4f}"
    row += f"  {r[-1]:>6.2f}n  {YT[ipk]/1e6:>8.0f}MPa"
    print(row)


# ============================================================
# PLOT STYLE — B&W journal style
# ============================================================
plt.rcParams.update({
    'figure.dpi':       150,
    'font.size':        11,
    'font.family':      'serif',
    'axes.labelsize':   12,
    'axes.titlesize':   13,
    'legend.fontsize':  9,
    'lines.linewidth':  1.5,
})

#   400 °C → ○   475 °C → △   500 °C → ▽   600 °C → □
MKR = {
    400: dict(marker='o', label='400 °C'),
    475: dict(marker='^', label='475 °C'),
    500: dict(marker='v', label='500 °C'),
    600: dict(marker='s', label='600 °C'),
}
MEV = max(1, data['n_points'] // 10)   # marker every ~10 % of points


def pcurve(ax, x, y, T, **kw):
    """Plot one temperature curve."""
    m = MKR[T]
    ax.plot(x, y, color='black', marker=m['marker'],
            markevery=MEV, markersize=6,
            markerfacecolor='white', markeredgecolor='black',
            markeredgewidth=1.0, label=m['label'], **kw)


# ============================================================
# FIG 2 — Equilibrium phase fractions vs Temperature
#   (A) Ni3Ti (ETA) phase fraction
#   (B) Reverted austenite (FCC) phase fraction
#   Data from full equilibrium sweep (BCC+FCC+ETA+LIQUID)
# ============================================================
if 'fig2_full_equilibrium' in data:
    print("\n[1/4] Generating Fig 2 (equilibrium phase fractions vs T) ...")

    fig2_data = data['fig2_full_equilibrium']
    T_C  = np.array(fig2_data['T_C'])
    fETA = np.array(fig2_data['f_ETA'])
    fFCC = np.array(fig2_data['f_FCC'])

    fig2, (a2A, a2B) = plt.subplots(1, 2, figsize=(12, 5))
    fig2.tight_layout(pad=3.5)

    # --- 2A: Ni3Ti fraction ---
    a2A.plot(T_C, fETA, color='black', linewidth=1.5)
    a2A.set_xlabel('Temperature ($\\degree$C)')
    a2A.set_ylabel('Phase fraction')
    a2A.set_title('(A)', fontweight='bold')
    a2A.set_xlim(0, 1750)
    a2A.set_ylim(bottom=-0.001)
    a2A.grid(False)

    # --- 2B: Reverted austenite (FCC) fraction ---
    a2B.plot(T_C, fFCC, color='black', linewidth=1.5)
    a2B.set_xlabel('Temperature ($\\degree$C)')
    a2B.set_ylabel('Phase fraction')
    a2B.set_title('(B)', fontweight='bold')
    a2B.set_xlim(0, 1750)
    a2B.set_ylim(-0.02, 1.05)
    a2B.grid(False)

    fig2.savefig('fig2_phase_fraction_vs_T.png', dpi=150, bbox_inches='tight')
    plt.close(fig2)
    print("  -> fig2_phase_fraction_vs_T.png")
else:
    print("\n[1/4] SKIPPED Fig 2 (no full equilibrium data in JSON)")


# ============================================================
# FIG 8 — Phase fractions vs time  (LINEAR x-axis, 0–5.5 h)
#   (A) Ni3Ti precipitate fraction
#   (B) Reverted austenite fraction
# ============================================================
print("\n[2/4] Generating Fig 8 (phase fractions) ...")

fig8, (a8A, a8B) = plt.subplots(1, 2, figsize=(12, 5))
fig8.tight_layout(pad=3.0)

# --- 8A: Ni3Ti fraction ---
for T in TEMPS:
    fp = np.array(kd[str(T)]['f_precip'])
    pcurve(a8A, t_h, fp, T)
a8A.set_xlabel('Time (hours)')
a8A.set_ylabel('Fraction of Ni$_3$Ti')
a8A.legend(loc='center right', framealpha=0.9)
a8A.set_title('(A)', fontweight='bold')
a8A.set_xlim(0, 5.5)
a8A.grid(False)

# --- 8B: Reverted austenite fraction ---
if has_gamma:
    for T in TEMPS:
        fg = np.array(kd[str(T)]['f_gamma'])
        pcurve(a8B, t_h, fg, T)
else:
    for T in TEMPS:
        fg_arr = np.zeros_like(t_h)
        pcurve(a8B, t_h, fg_arr, T)
    a8B.text(0.5, 0.5, 'f$_\\gamma$ = 0 (not modeled)',
             transform=a8B.transAxes, ha='center', va='center',
             fontsize=10, color='gray', style='italic')

a8B.set_xlabel('Time (hours)')
a8B.set_ylabel('Fraction of reverted austenite')
a8B.legend(loc='center right', framealpha=0.9)
a8B.set_title('(B)', fontweight='bold')
a8B.set_xlim(0, 5.5)
a8B.grid(False)

fig8.savefig('fig8_phase_fractions.png', dpi=150, bbox_inches='tight')
plt.close(fig8)
print("  -> fig8_phase_fractions.png")


# ============================================================
# FIG 9 — Precipitate radius and aspect ratio vs time
#   (A) Radius
#   (B) Aspect ratio
# ============================================================
print("\n[3/4] Generating Fig 9 (radius + aspect ratio) ...")

fig9, (a9A, a9B) = plt.subplots(1, 2, figsize=(12, 5))
fig9.tight_layout(pad=3.0)

# --- 9A: Radius ---
for T in TEMPS:
    r_nm = np.array(kd[str(T)]['r_nm'])
    pcurve(a9A, t_h, r_nm, T)
a9A.set_xlabel('Time (hours)')
a9A.set_ylabel('Radius of Ni$_3$Ti (nm)')
a9A.legend(loc='center right', framealpha=0.9)
a9A.set_title('(A)', fontweight='bold')
a9A.set_xlim(0, 5.5)
a9A.grid(False)

# --- 9B: Aspect ratio ---
if has_ar:
    for T in TEMPS:
        ar = np.array(kd[str(T)]['ar'])
        pcurve(a9B, t_h, ar, T)
else:
    for T in TEMPS:
        ar_arr = np.ones_like(t_h)
        pcurve(a9B, t_h, ar_arr, T)
    a9B.text(0.5, 0.5, 'ar = 1.0 (not modeled)',
             transform=a9B.transAxes, ha='center', va='center',
             fontsize=10, color='gray', style='italic')

a9B.set_xlabel('Time (hours)')
a9B.set_ylabel('Aspect ratio of Ni$_3$Ti')
a9B.legend(loc='center right', framealpha=0.9)
a9B.set_title('(B)', fontweight='bold')
a9B.set_xlim(0, 5.5)
a9B.grid(False)

fig9.savefig('fig9_radius_aspect.png', dpi=150, bbox_inches='tight')
plt.close(fig9)
print("  -> fig9_radius_aspect.png")


# ============================================================
# FIG 10 — Yield strength vs time (ISOTHERMAL AGEING ONLY)
#   (A) Total yield strength YT
#   (B) Precipitation strengthening σP only
# ============================================================
print("\n[4/4] Generating Fig 10 (yield strength) ...")

fig10, (a10A, a10B) = plt.subplots(1, 2, figsize=(12, 5))
fig10.tight_layout(pad=3.0)

# --- 10A: Total yield strength ---
for T in TEMPS:
    t_ramp_s = kd[str(T)]['t_ramp_s']
    idx_iso = t_s >= t_ramp_s
    t_iso_h = (t_s[idx_iso] - t_ramp_s) / 3600.0
    YT = np.array(kd[str(T)]['YT_Pa'])[idx_iso]
    pcurve(a10A, t_iso_h, YT / 1e6, T)
a10A.axhline(Y_alpha / 1e6, color='black', lw=1.0, ls='-',
             label=f'Y$_\\alpha$ = {Y_alpha/1e6:.0f} MPa')
a10A.set_xlabel('Time (hours)')
a10A.set_ylabel('Yield strength (MPa)')
a10A.legend(loc='best', framealpha=0.9, fontsize=8)
a10A.set_title('(A)', fontweight='bold')
a10A.set_xlim(0, 5)
a10A.grid(False)

# --- 10B: Precipitate-only σP ---
for T in TEMPS:
    t_ramp_s = kd[str(T)]['t_ramp_s']
    idx_iso = t_s >= t_ramp_s
    t_iso_h = (t_s[idx_iso] - t_ramp_s) / 3600.0
    sP = np.array(kd[str(T)]['sigma_P_Pa'])[idx_iso]
    pcurve(a10B, t_iso_h, sP / 1e6, T)
a10B.set_xlabel('Time (hours)')
a10B.set_ylabel('$\\sigma_P$ (MPa)')
a10B.legend(loc='center right', framealpha=0.9)
a10B.set_title('(B)', fontweight='bold')
a10B.set_xlim(0, 5)
a10B.grid(False)

fig10.savefig('fig10_yield_strength.png', dpi=150, bbox_inches='tight')
plt.close(fig10)
print("  -> fig10_yield_strength.png")


# ============================================================
# DONE
# ============================================================
print("\n" + "=" * 70)
print("  ALL FIGURES SAVED:")
for fn in ['fig2_phase_fraction_vs_T.png',
           'fig8_phase_fractions.png',
           'fig9_radius_aspect.png',
           'fig10_yield_strength.png']:
    exists = os.path.exists(fn)
    sz = os.path.getsize(fn) if exists else 0
    print(f"    {'[OK]' if exists else '[!!]'}  {fn:35s}  ({sz:>8,d} bytes)")
print("\n  Data source: pipeline_full_timeseries.json")
print("=" * 70)
